### ISSUE TITLE
Trezor enumerate not working

### ISSUE THREAD

**Issue by instagibbs** [achow101/HWI#36]
```
./hwi.py enumerate
INFO:trezorlib.transport:looking for device by full path: hid:0001:0010:00
INFO:trezorlib.client:creating client instance for device: hid:0001:0010:00
INFO:trezorlib.transport:looking for device by full path: hid:0001:0010:01
Traceback (most recent call last):
  File "./hwi.py", line 11, in <module>
    result = process_commands(sys.argv[1:])
  File "/home/greg/bitcoin-dev/HWI/hwilib/commands.py", line 223, in process_commands
    return args.func()
  File "/home/greg/bitcoin-dev/HWI/hwilib/commands.py", line 86, in enumerate
    client = get_client(d_data['type'], d_data['path'])
  File "/home/greg/bitcoin-dev/HWI/hwilib/commands.py", line 41, in get_client
    client = trezori.TrezorClient(device=device, path=device_path)
  File "/home/greg/bitcoin-dev/HWI/hwilib/trezori.py", line 55, in __init__
    self.client = Trezor(transport=get_transport("hid:"+path.decode()))
  File "/home/greg/.local/lib/python3.5/site-packages/trezorlib/transport/__init__.py", line 118, in get_transport
    return transports[0].find_by_path(path, prefix_search=prefix_search)
  File "/home/greg/.local/lib/python3.5/site-packages/trezorlib/transport/__init__.py", line 67, in find_by_path
    raise TransportException('{} device not found: {}'.format(cls.PATH_PREFIX, path))
trezorlib.transport.TransportException: hid device not found: hid:0001:0010:01
```

**Comment by achow101** [comment]
I am unable to replicate. Did you install the dependencies correctly? You need to have `hidapi`.

**Comment by instagibbs** [comment]
Made sure I had hidapi installed, still have the issue.

**Comment by instagibbs** [comment]
Ok it seems to be happening when it finds the second hid path: "hid:0001:0010:01"

If I do a short-cut return before that, it returns what I'm guessing is correct output:
```
[{"fingerprint": "c5d214ab", "path": "0001:0009:00", "type": "trezor", "serial_number": "8683012948059C9758715A86"}]
```
